### ISSUE TITLE
WARN comments for timezone

### ISSUE THREAD

**Issue by polytan02** [fmbiete/Z-Push-contrib#221]
I have these kind of ocmments when I connect my devices : 

``10/08/2015 20:08:44 [31338] [INFO] [user-hidden] Version='SVN-trunk-r1975' method='POST' from='ipv4-hidden' cmd='Sync' getUser='domain-hidden\user-hidden' devId='devid-hidden' devType='PlayBook'
10/08/2015 20:08:45 [31338] [INFO] [user-hidden] ExportChangesDiff->InitializeExporter(): Found 1 changes
10/08/2015 20:08:45 [31338] [WARN] [user-hidden] /var/www/z-push/lib/utils/timezoneutil.php:1115 Undefined index: Europe/London (8)
10/08/2015 20:08:45 [31338] [WARN] [user-hidden] TimezoneUtil::getMSTZnameFromTZName() no MS name found for 'Europe/London'. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
10/08/2015 20:08:45 [31338] [WARN] [user-hidden] TimezoneUtil::getMSTZnameFromTZName() no MS name found for 'Europe/London'. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
``

or

``10/08/2015 21:48:00 [16582] [WARN] [user-hidden] /var/www/z-push/lib/utils/utils.php:1005 timezone_open(): Unknown or bad timezone ((GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London) (2)
``

Is it concerning ?

**Comment by fmbiete** [comment]
They are not critical, but I should fix it.

Can you post the calendar DAV that is causing it? I need the timezone so I can figure why is not encoded correctly.

Thanks!!

**Comment by polytan02** [comment]
The calcard dav server is Baikal.

The timezone on the server is setup at Europe/London.

Do you need any further info?

**Comment by fmbiete** [comment]
Yes, I need the text/calendar part from your message (or the text represantion for your dav object).
Something like this:

```
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Romance Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=Pablo Marmol:MAILTO:pablo.marmol@zpush.org
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;CN=Name1 Sur
 name2:MAILTO:user1@zpush.org
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Name1
  Surname2:MAILTO:user2@zpush.org
DESCRIPTION;LANGUAGE=es-ES:Texto de la segunda cita\n\n
SUMMARY;LANGUAGE=es-ES:Segunda cita
DTSTART;TZID=Romance Standard Time:20140519T090000
DTEND;TZID=Romance Standard Time:20140519T093000
UID:040000008200E00074C5B7101A82E0080000000070BC3EB80871CF01000000000000000
 010000000B3492E4691795F4E810CCD60A178B53C
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20140516T111408Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=es-ES:Oficina
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:860903390
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Comment by polytan02** [comment]
So, I have done another test : 

14/08/2015 17:34:23 [11060] [INFO] [user1] ExportChangesDiff->InitializeExporter(): Found 1 changes
14/08/2015 17:34:23 [11060] [WARN] [user1] /var/www/z-push/lib/utils/timezoneutil.php:1115 Undefined index: Europe/Dublin (8)
14/08/2015 17:34:23 [11060] [WARN] [user1] TimezoneUtil::getMSTZnameFromTZName() no MS name found for 'Europe/Dublin'. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
14/08/2015 17:34:23 [11060] [WARN] [user1] TimezoneUtil::getMSTZnameFromTZName() no MS name found for 'Europe/Dublin'. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
14/08/2015 17:34:24 [ 9198] [INFO] [user1] Version='SVN-trunk-r1981' method='POST' from='ipv4-hidden' cmd='Ping' getUser='domain.tld\user1' devId='id-hidden' devType='BlackBerry'


BEGIN:VCALENDAR
PRODID:-//Research In Motion//RIM App//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/Dublin
BEGIN:STANDARD
DTSTART:20001029T020000
RRULE:FREQ=3DYEARLY;BYDAY=3D4SU;BYMONTH=3D10
TZNAME:GMT
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20000326T010000
RRULE:FREQ=3DYEARLY;BYDAY=3D4SU;BYMONTH=3D3
TZNAME:IST
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;RSVP=3DTRUE;ROLE=3DREQ-PARTICIPANT;CN=3Dmaxtest@mcgva.ovh;PARTSTAT=
=3DTENTATIVE
 :mailto:user1@domain.tld
CREATED:20150814T163344Z
DTEND;TZID=3DEurope/Dublin:20150814T175000
DTSTAMP:20150814T163344Z
DTSTART;TZID=3DEurope/Dublin:20150814T174500
ORGANIZER:mailto:user2@domain.tld
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Test invitation
TRANSP:OPAQUE
UID:3af267ec-42a2-11e5-bfc0-574eadb945a2
END:VEVENT
END:VCALENDAR

**Comment by fmbiete** [comment]
The referenced commit should fix the problem for Blackberry devices.
Let me know if it works. Thanks!!

**Comment by polytan02** [comment]
Hi pulled the updated files and installed the update I still have the bug (apparently). 
Also, a second one apparead, not sure if I have to open a dedicated thread, please let me know.


I'm definitely keen on helping to sort out this issue and have a working meeting/caldav backend working.

To run the tests, I have 3 servers (different ones but all running the same config based on debian 7 or 8, with yunohost, baikal as card and cal dav, postfix, dovecot and of course, z-push) and 3 accounts (one each).
The devices are : 
- Blackberry Passport running ActiveSync
- Blackberry Playbook
- Win10 with the native basic mail app (very basic app where I actually can't see a meeting request (boring) nor an answer to a meeting created. Would anybody advise a decent/simple activesync client for windows so that I could properly run the tests ?

I don't see any issue when I send or receive the invitation, but it the timezone bug appears when one device accepts (and add a little text in option) and send the invit.

Also, it may be linked, but I have this issue also : 
16/08/2015 19:29:42 [18008] [ERROR] [user3] BackendIMAP->update_calendar_attendee(): event not found or duplicated event

I wanted to open another thread, but I think both are linked.

It seems that my devices don't recognise an answer to an invit ... as an answer. They recreate the meeting.

**Comment by polytan02** [comment]
On my BB Passport, the answer I receive from the Playbooks states that "This is an aswer to a meeting request which doesn't contain all the details of the meeting".

Original meeting request : 
BEGIN:VCALENDAR
PRODID:-//Research In Motion//RIM App//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/London
BEGIN:STANDARD
DTSTART:20121028T020000
RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=10
TZNAME:GMT
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20130331T010000
RRULE:FREQ=YEARLY;BYDAY=5SU;BYMONTH=3
TZNAME:BST
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CN=user3@domain3.xyz;PARTSTAT=NEEDS-AC
 TION:mailto:user3@domain3.xyz
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CN=user2@domain2.ovh;PARTSTAT=NEEDS-ACT
 ION:mailto:user2@domain2.ovh
CREATED:20150816T183329Z
DTEND;TZID=Europe/London:20150816T215500
DTSTAMP:20150816T183329Z
DTSTART;TZID=Europe/London:20150816T205500
LOCATION:Home
ORGANIZER:mailto:user1@domain1.org
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:A 3rd test
TRANSP:OPAQUE
UID:4a6f3226-4445-11e5-bf1c-1b904dc27b40
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:A 3rd test in 15 minutes.
TRIGGER;RELATED=START:-PT15M
X-WR-ALARMUID:4afad054-4445-11e5-bf86-1b904dc27b40
END:VALARM
END:VEVENT
END:VCALENDAR

Answer received : 

BEGIN:VCALENDAR
PRODID:-//Research In Motion//RIM App//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REPLY
BEGIN:VTIMEZONE
TZID:Europe/London
BEGIN:STANDARD
DTSTART:20001029T020000
RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=10
TZNAME:GMT
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20000326T010000
RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=3
TZNAME:BST
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CN=user2@domain2.ovh;PARTSTAT=ACCEPTED:
 mailto:user2@domain2.ovh
COMMENT:oki
CREATED:20150816T184932Z
DTEND;TZID=Europe/London:20150816T215500
DTSTAMP:20150816T184933Z
DTSTART;TZID=Europe/London:20150816T205500
LOCATION:Home
ORGANIZER:mailto:user1@domain1.org
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:A 3rd test
TRANSP:OPAQUE
UID:4a6f3226-4445-11e5-bf1c-1b904dc27b40
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:A 3rd test in 15 minutes.
TRIGGER;RELATED=START:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by fmbiete** [comment]
Hi @polytan02 ,

Can you send me your log files for both issues? fbiete at gmail dot com

**Comment by polytan02** [comment]
Do you want the full log with th debug option or just the normal one ?

**Comment by fmbiete** [comment]
WBXML level will be more useful

**Comment by polytan02** [comment]
I will do my best this weekend to get t logs for you.

Don't you and the issue one your side ?

**Comment by fmbiete** [comment]
No. The problem with this issue is the timezone. Blackberry uses PHP timezones (Europe/Berlin), but Android, Outlook, Thunderbird and Roundcube use the timezones that z-push are expecting (Romance Standard Time).

**Comment by polytan02** [comment]
Logs sent via email

**Comment by polytan02** [comment]
@fmbiete Have you been able to look at the logs to see why we the answer to a meeting is not recognised on BlackBerry ?

**Comment by PhilPhonic** [comment]
I am having the same problem on my iPhone 5 (iOS 8.4.1) with DAViCal.

> 05/12/2015 17:49:34 [ 3873] [INFO] [user@example.com] ExportChangesDiff->InitializeExporter(): Found '69' changes for 'Ccalendar'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
> 05/12/2015 17:49:34 [ 3873] [WARN] [user@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'

**Comment by fmbiete** [comment]
@PhilPhonic  Can you post your DAV object, please??

**Comment by PhilPhonic** [comment]
How do I do that?

**Comment by fmbiete** [comment]
You can get the DAV object from your WBXML log, or directly from your DAV server.

**Comment by polytan02** [comment]
@fmbiete by DAV object, do you mean the content of the calendar invite he received ?

**Comment by fmbiete** [comment]
Yes @polytan02 the same you did some comments up :smile:

**Comment by polytan02** [comment]
I just wanted to confirm to help @PhilPhonic ;)

**Comment by PhilPhonic** [comment]
hope this is what you need:
> 06/01/2016 10:40:57 [23567] [ INFO] [mail@example.com] ExportChangesDiff->InitializeExporter(): Found '71' changes for 'Ccalendar'
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] Folder type: Calendar
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O  <Synchronize>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O   <Folders>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O    <Folder>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     <SyncKey>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     {f5391a3e-71a6-4dc2-a59e-9a54d9a8e38a}2
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     </SyncKey>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     <FolderId>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     c/Ccalendar
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     </FolderId>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     <Status>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     1
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     </Status>
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] LoopDetection->Detect(): UUID changed for folder
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] LoopDetection->Detect(): UUID changed and while items where sent to device - forcing loop mode
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] LoopDetection->Detect(): case 3.1 detected - loop detected, init loop mode
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] LoopDetection->Detect(): loop data: loopcount(1), maxCount(26), queued(71), ignored(false)
06/01/2016 10:40:57 [23567] [ WARN] [mail@example.com] Mobile loop detected! Messages sent to the mobile will be restricted to 1 items in order to identify the conflict
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     <MoreAvailable/>
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] BackendCalDAV->StatMessage('Ccalendar','20160101T002433Z-ddc7e05012ceee33b1487a773aa6fbe3.ics')
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] BackendCalDAV->GetMessage('Ccalendar','20160101T002433Z-ddc7e05012ceee33b1487a773aa6fbe3.ics')
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] BackendCalDAV->_ParseVEventToAS(): Parsing VEvent
06/01/2016 10:40:57 [23567] [ WARN] [mail@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
06/01/2016 10:40:57 [23567] [ WARN] [mail@example.com] TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] BackendCalDAV->_ParseVEventToSyncObject(): 'X-MICROSOFT-CDO-ALLDAYEVENT' is not yet supported.
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] BackendCalDAV->_ParseVEventToSyncObject(): No organizeremail defined, using username
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] LoopDetection->IgnoreNextMessage(): Loop mode, potential broken message id '20160101T002433Z-ddc7e05012ceee33b1487a773aa6fbe3.ics'
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     <Perform>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O      <Add>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O       <ServerEntryId>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O       20160101T002433Z-ddc7e05012ceee33b1487a773aa6fbe3.ics
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O       </ServerEntryId>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O       <Data>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:Timezone>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        xP///0NFVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAFAAEAAAAAAAAAAAAAAENFU1QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAFAAEAAAAAAAAAxP///w==
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:Timezone>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:DtStamp>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        20160101T002432Z
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:DtStamp>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:StartTime>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        20161225T110000Z
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:StartTime>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:Subject>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        SchÃ¼Ã¼Ã¼ Ente machen!
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:Subject>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:UID>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        20160101T002433Z-ddc7e05012ceee33b1487a773aa6fbe3
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:UID>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:OrganizerEmail>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        mail@example.com
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:OrganizerEmail>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:EndTime>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        20161225T120000Z
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:EndTime>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:Sensitivity>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        0
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:Sensitivity>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        <POOMCAL:BusyStatus>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        2
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O        </POOMCAL:BusyStatus>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O       </Data>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O      </Add>
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] HandleSync(): Exported maxItems of messages: 1 / 71
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O     </Perform>
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] SetFolderSyncStatus(): set 2 for c/Ccalendar
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O    </Folder>
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] SqlStateMachine->SetState(): 'device', '', 'f5391a3e-71a6-4dc2-a59e-9a54d9a8e38a', '2'
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] SyncCollections->SaveCollection(): Data of folder 'c/Ccalendar' changed
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] SqlStateMachine->SetState(): 'device', 'fd', 'f5391a3e-71a6-4dc2-a59e-9a54d9a8e38a', ''
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O   </Folders>
06/01/2016 10:40:57 [23567] [WBXML] [mail@example.com] O  </Synchronize>
06/01/2016 10:40:57 [23567] [DEBUG] [mail@example.com] WBXMLEncoder->endTag() WBXML output completed

**Comment by fmbiete** [comment]
No, it's not. Is something like the https://github.com/fmbiete/Z-Push-contrib/issues/221#issuecomment-131174538.
Although in your log says that we have an empty timezone:
```
TimezoneUtil::getMSTZnameFromTZName() no MS name found for ''.
```

**Comment by PhilPhonic** [comment]
can't find something like that in my WBXML log :-(
